// Bakers Delight's real, current product range -- 174 products, confirmed
// by paging through every page of https://www.bakersdelight.com.au/
// collections/all-products (page 9 returns "No products found", i.e.
// exhaustive) on 2026-09-13. Used only to ground the LLM strategist's
// product-fit reasoning in src/llmStrategist.js -- it must never suggest a
// product that isn't in this list, and this list must never be invented.
//
// Price is only included for the 24 products where it's confirmed from the
// site's own tracking data (page 1) -- never fabricated for the rest.
const PRODUCTS = [
  { name: 'Round White Roll', price: 1.10 },
  { name: 'White Long Roll', price: 1.10 },
  { name: 'Traditional Scone', price: 3.00 },
  { name: 'Hi-Fibre Lo-GI White Block Loaf', price: 5.90 },
  { name: 'Vanilla Slice Scroll', price: 4.80 },
  { name: 'Cheesymite Scroll', price: 4.50 },
  { name: 'White Dinner Roll', price: 0.90 },
  { name: 'Spinach & Fetta Twisted Delight', price: 7.80 },
  { name: 'Italian Roll', price: 3.90 },
  { name: 'White Block Loaf', price: 5.00 },
  { name: 'Hi-Fibre Lo-GI Wholemeal Block Loaf', price: 5.90 },
  { name: 'Mini Cheesymite Scroll 4 Pack', price: 8.60 },
  { name: 'White Knot Roll', price: 1.10 },
  { name: 'Mediterranean Pizza', price: 5.60 },
  { name: 'Hi-Fibre Lo-GI Round Roll', price: 1.30 },
  { name: 'Hi-Fibre Lo-GI White Lunch Box Roll 6 Pack', price: 5.60 },
  { name: 'Croissant', price: 3.90 },
  { name: 'Hi-Protein Low Carb Wholegrain Round Roll', price: 1.50 },
  { name: 'Sticky Cinnamon Scroll', price: 4.70 },
  { name: 'Mini Custard Scroll 4 Pack', price: 8.60 },
  { name: 'Sourdough Vienna', price: 8.00 },
  { name: 'Margherita Pizza', price: 5.60 },
  { name: 'Hi-Protein Low Carb Wholegrain Block Loaf', price: 6.70 },
  { name: 'Croissant 4 Pack', price: 14.40 },
  // Remaining 150 -- names confirmed from the live site, price not
  // captured (none invented).
  { name: 'Apple & Walnut Log' },
  { name: 'BBQ Sauce Savoury Bite' },
  { name: 'BBQ Bonanza Pizza' },
  { name: 'Cheese & Bacon Roll' },
  { name: 'White Round Roll 6 Pack' },
  { name: 'Lunch Box Fillers Combo (with Mini Roll 6 Pack)' },
  { name: 'Savoury Bite 3 Pack' },
  { name: 'Pizza 2 Pack' },
  { name: 'Traditional Dinner Roll 6 Pack' },
  { name: 'Scone 6 Pack' },
  { name: 'Scone 4 Pack' },
  { name: 'Pepperoni Pizza' },
  { name: 'White Hot Dog Roll' },
  { name: 'Mini Cheese & Tomato Savoury Roll 6 Pack' },
  { name: 'Wholemeal Flour Loaf' },
  { name: 'White Cob' },
  { name: 'White Table Roll' },
  { name: 'Sourdough Roll' },
  { name: 'White Pipe Loaf' },
  { name: 'White High Tin Loaf' },
  { name: 'Pane di Casa Vienna Roll' },
  { name: 'Pink Fondant Fun Bun' },
  { name: 'Seeded Turkish Baguette' },
  { name: 'Sea Salt Turkish Baguette' },
  { name: 'Veggie Pizza' },
  { name: 'Wholemeal Small Block Loaf' },
  { name: 'Mixed Seed Sourdough Vienna' },
  { name: 'Sea Salt Turkish Loaf' },
  { name: 'Sesame Seeds Turkish Bread Roll' },
  { name: 'Mocha Hot Cross Bun' },
  { name: 'Lemon Tart' },
  { name: 'Pink Fondant Finger Bun' },
  { name: 'Portuguese Custard Tart 4 Pack' },
  { name: 'Wholemeal Round Roll' },
  { name: 'Traditional Hot Cross Bun' },
  { name: 'Traditional Hot Cross Bun 6 Pack' },
  { name: 'White Mini Pizza Base 4 Pack' },
  { name: 'Rye Sourdough Vienna' },
  { name: 'Large Traditional Christmas Cake' },
  { name: 'Pink Fondant and 100s & 1000s Fun Bun' },
  { name: 'Mini Jam Donut 6 Pack' },
  { name: 'White Farmers Loaf' },
  { name: 'White Pizza Base 2 Pack' },
  { name: 'Large Sesame Seed Turkish Bread' },
  { name: 'Sourdough Baguette' },
  { name: 'Mini Margherita Scroll 4 Pack' },
  { name: 'Mocha Hot Cross Bun 6 Pack' },
  { name: 'White Breadstick' },
  { name: 'Lemon Tart 6 Pack' },
  { name: 'Small Traditional Christmas Cake' },
  { name: 'Portuguese Custard Tart' },
  { name: 'White Hamburger Roll' },
  { name: 'Sea Salt Flakes Turkish Bread Roll' },
  { name: 'Mixed Seed Sourdough High Tin Loaf' },
  { name: 'Large Sea Salt Flakes Turkish Bread' },
  { name: 'White Tiger Roll' },
  { name: 'Mini Cheese & Bacon Roll 6 Pack' },
  { name: 'Supreme Pizza' },
  { name: 'Pane di Casa Vienna Loaf' },
  { name: 'Wholegrain LowFOD™ Roll' },
  { name: 'White Big Block Loaf' },
  { name: 'White Tin Vienna' },
  { name: 'Wholemeal Vienna' },
  { name: 'Wholemeal Tin Vienna' },
  { name: 'White Country Grain Block Loaf' },
  { name: 'Wholemeal Block Loaf' },
  { name: 'White Small Block Loaf' },
  { name: 'Spinach & Fetta Danish' },
  { name: 'Pizza Sauce Savoury Bite' },
  { name: 'White Flour Loaf' },
  { name: 'Cruffin Made with KITKAT' },
  { name: 'Cruffin Made with KITKAT 4 Pack' },
  { name: 'Choc Hazelnut Cruffin' },
  { name: 'Easter Artisan Essentials Combo' },
  { name: 'Delicious Dozen Combo' },
  { name: 'Everyday Loaves 2 Pack' },
  { name: 'Everyday Rolls 12 Pack' },
  { name: '2 x Specialty Health Loaves' },
  { name: 'Ciabatta Roll' },
  { name: 'Apple & Cinnamon Hot Cross Bun' },
  { name: 'Berry & Custard Teatime' },
  { name: 'Apple Log' },
  { name: 'Custard Cruffin' },
  { name: 'Choc Chip Hot Cross Bun' },
  { name: 'Cinnamon & Fruit Small Block Loaf' },
  { name: 'Cheese & Olive Roll' },
  { name: 'Continental Dark Rye Loaf' },
  { name: 'Apple & Cinnamon Loaf' },
  { name: 'Herb Turkish Bread Roll' },
  { name: 'Cape Seed Loaf' },
  { name: 'Fruit Bun' },
  { name: 'Boston Filled Fruit Bun' },
  { name: 'Custard Danish Lattice' },
  { name: 'Cheese & Bacon Twisted Delight' },
  { name: 'Ham & Mustard Pickle Twirl' },
  { name: 'Chia Omega-3 Wholemeal Block Loaf' },
  { name: 'Boston Icing & Coconut Finger Bun' },
  { name: 'Apricot Delight High Tin Loaf' },
  { name: 'Garlic, Black Pepper & Parmesan Rodini' },
  { name: 'Boston Bun' },
  { name: 'Custard & Apple Teatime' },
  { name: 'Continental Pasta Dura' },
  { name: 'Fruitless Hot Cross Bun' },
  { name: 'Boston Icing & Coconut Fun Bun' },
  { name: 'Continental Hungarian Roll' },
  { name: 'BCNA Fun Bun' },
  { name: 'Cheese Roll' },
  { name: 'Coffee Scroll' },
  { name: 'Brioche Slider' },
  { name: 'Custard & Almond Log' },
  { name: 'Blueberry Teatime' },
  { name: 'Continental Hungarian Parmesan Roll' },
  { name: 'Hi-Fibre Lo-GI Wholemeal Round Roll' },
  { name: 'Challah Plait' },
  { name: 'Continental Tin Pasta Dura' },
  { name: 'Glazed Lemon & Blueberry Scone' },
  { name: 'Cape Seed Small Loaf' },
  { name: 'French Baguette' },
  { name: 'Apple & Custard Scroll' },
  { name: 'Brioche Hamburger Bun' },
  { name: 'BCNA Fun Bun 6 Pack' },
  { name: 'Boston Icing & 100s & 1000s Fun Bun' },
  { name: 'Apple & Walnut Scroll' },
  { name: 'Ciabatta Loaf' },
  { name: 'Custard & Almond Scroll' },
  { name: 'Apple & Cinnamon Hot Cross Bun 6 Pack' },
  { name: 'Chive & Garlic Twisted Delight' },
  { name: 'Herb & Garlic White Sub Roll' },
  { name: 'Fruitless Hot Cross Bun 6 Pack' },
  { name: 'Hi-Fibre Lo-GI White Small Block Loaf' },
  { name: 'Cinnamon Log' },
  { name: 'Apple & Custard Log' },
  { name: 'Hi-Fibre Lo-GI Wholemeal Small Block Loaf' },
  { name: 'Escargot' },
  { name: 'Custard & Almond Teatime' },
  { name: 'Apple Scroll' },
  { name: 'Choc Chip Hot Cross Bun 6 Pack' },
  { name: 'Cape Seed Roll' },
  { name: 'Chilli Mexicana Pizza' },
  { name: 'Apple Pie Danish' },
  { name: 'Gherkin Savoury Bite' },
  { name: 'Fruit Mince Tart' },
  { name: 'Cinnamon & Fruit Block Loaf' },
  { name: 'Chocolate Croissant' },
  { name: 'Ham & Cheese Danish' },
  { name: 'Choc Mud Scone' },
  { name: 'Berry & White Choc Scone' },
  { name: 'Date Scone' },
  { name: 'Custard Scroll' },
  { name: 'Hawaiian Pizza' }
];

module.exports = { PRODUCTS };
